In [3]:
import numpy as np
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [16]:
import numpy 
lst1 = [] 
lst2 = []  
for i in range(0, 5): 
    ele1 = int(input()) 
    lst1.append(ele1)
for j in range(0, 5): 
    ele2 = int(input()) 
    lst2.append(ele2) 
arr1 = numpy.array(lst1)
arr2 = numpy.array(lst2)
arr=np.concatenate((arr1, arr2))
print ("Array: ", arr)
arr.sort() 
print(arr) 

3
2
5
6
7
8
9
4
1
10
Array:  [ 3  2  5  6  7  8  9  4  1 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [17]:
import numpy as np
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print("No. of dimensions: ", arr.ndim)
print("Size of array: ", arr.size)

No. of dimensions:  2
Size of array:  6


In [18]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (2, 5))
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
import numpy as np 
  
arr1 = [3,9] 
arr2=np.square(arr1)
arr3 = [8,7] 
arr4=np.square(arr3)
arr5=np.vstack(arr2)
arr6=np.hstack(arr2)
arr7=np.vstack(arr4)
arr8=np.hstack(arr4)
print(arr5)
print(arr6)
print(arr7)
print(arr8)

[[ 9]
 [81]]
[ 9 81]
[[64]
 [49]]
[64 49]


In [27]:
input_list = [1, 2, 2, 5, 8, 4, 4, 8] 
  
# taking an input list 
l1 = [] 
  
# taking an counter 
count = 0
  
# travesing the array 
for item in input_list: 
    if item not in l1: 
        count += 1
        l1.append(item) 
print(l1)
# printing the output 
print("No of unique items are:", count) 

[1, 2, 5, 8, 4]
No of unique items are: 5
